go:
    version: 1.21
repository:
    path: github.com/iamgeef/prometheus-amazon-workspaces-sd
build:
    binaries:
        - name: prometheus-amazon-workspaces-sd
          path: .
    flags: -a -tags netgo
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser=prometheus@amazon-workspaces-sd
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    prefix: .
    files:
        - LICENSE
        - README.md
crossbuild:
    platforms:
        - linux/amd64
        - darwin/amd64
        - freebsd/amd64
        - linux/arm
        - linux/arm64
        - freebsd/arm
