{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-amazon-workspaces-sd.serviceAccountName" . }}
  labels:
{{ include "prometheus-amazon-workspaces-sd.labels" . | nindent 4 }}
{{- end -}}
